language: r
pandoc_version: 1.18
sudo: false
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
- git config --global user.email "christoph.molnar@gmail.com"
- git config --global user.name "Christoph Molnar"
script: ./_deploy.sh
env:
  global:
    secure: CgboZO9HV2q4ZNgoCRGzA5wHTt91EjI24JoT3FIJAqlMczPRsP1X6hhar/BfkxTt4bt9cOZUKpW73nCZlynGVFcSaH/JXBqVC48JlWlm+WPHQHoZ8hl2CXarc+YCK+dkIrlEjejOBb7TVuGFjweMVgcKP8Vu1GgDjaxyRXDloV+G7nPSvQlyI/63MLVw/G5rqm6eOaCYWyDtJAT0f2pMxw1EFc6TJ6lTMPcnlS3kmv9b4BpvIMCPnd9RtkBD3A0ha60OuXMHNCXcqbaJT7wA+AOqf7wvvhJxXUU1yHRYVXwEXgj89tXvKuEpjqP2ij2lm7nxbpqVxApwCMraBOJrdzQSkcQjc79YIk+P8kc3WabTnYembkPAHN1P+4kIjwIVfUcgYqa3yPwjlwZYMPnjG8czoSywrWpq/VMn8bGDh/GnDhxibvFqSeqsFpQAW+xfKsW3HbV5SBwq+A52tM0CTD3zLYtcQ7zmlMd9y/IxkwUKrmX6baw8663TelpPnjB549akxNvaba8WI+CnV7wOToeEUoQUGoOJK+X7whq32g/obIw1XEaKyt4w+7SRDT9BnKZJZHSkp1HxUfr4mpgLI1x5Q7duueVDD0cGhi+xf8D7ZVios1BBW5AajKWjWPVX89aOvwBbLMowPSBT1GMJlxJiHbxScaAFYgdnJUGIhUM=
